import type { NextPage } from 'next'
import Head from 'next/head'
import App from './_app'
import styles from '../styles/Home.module.css'
import { useSelector, useDispatch } from 'react-redux'
import { Actions } from 'store'
import wineList from 'mocks/wineList'
import ProductList from 'components/ProductList'


const Catalog: NextPage = () => {
  const {app} = useSelector((state) => state);
  const dispatch = useDispatch();

  return (
    <div className={styles.container}>
      <Head>
        <title>Vinhos com descontos especiais | Wine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProductList list={wineList}>

        </ProductList>
      </main>
    </div>
  ) 
}

export default Catalog
