import type { NextPage } from 'next'
import Head from 'next/head'
import App from './_app'
import {Container} from 'styles'
import { useSelector, useDispatch } from 'react-redux'
import { Actions } from 'store'
import ProductList from 'components/ProductList'
import Filter from 'components/Filter'
import { useEffect } from 'react'
import { useRouter } from 'next/router'
import { FilterCodes } from 'types';
import {getQueryVariable} from 'utils/getQueryVariable'

const Catalog: NextPage = () => {
  const {app, products} = useSelector((state) => state);
  const dispatch = useDispatch();
  const router = useRouter()
  const search = router.asPath.split('?')[1]
  useEffect(() => {
    let shouldJustLoad = true
    products.priceFilters.forEach(price => {
      if (search?.indexOf('filter=' + price.queryString) > -1) {
        shouldJustLoad = false
        return dispatch({
          type: Actions.CHANGE_PRICE_FILTER,
          payload: {
            id: price.id,
            page: getQueryVariable('page')
          }
        })
      } 
    })
    if (getQueryVariable('name')) {
      shouldJustLoad = false
      dispatch({
        type: Actions.SEARCH_PRODUCTS,
        payload: {
          search: getQueryVariable('name'),
          page: getQueryVariable('page')
        }
      }) 
    }
    if (shouldJustLoad) {
      dispatch({
        type: Actions.LOAD_PRODUCTS,
        payload: {
          page: getQueryVariable('page') || 1,
          queryString: '' + getQueryVariable('search') ? '&search=' + getQueryVariable('search') : '' + getQueryVariable('filter') ? '&filter=' + getQueryVariable('filter') : ''
        }
      })
    }
  }, [])
  useEffect(() => {
    dispatch({
      type: Actions.LOAD_CART
    })
  }, [])
  return (
    <>
      <Head>
        <title>Vinhos com descontos especiais | Wine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Filter />
        <ProductList list={products.productsList} />
      </Container>
    </>
  ) 
}

export default Catalog
