import type { NextPage } from 'next'
import Head from 'next/head'
import App from './_app'
import {Container} from 'styles'
import { useSelector, useDispatch } from 'react-redux'
import { Actions } from 'store'
import wineList from 'mocks/wineList'
import ProductList from 'components/ProductList'
import Filter from 'components/Filter'
import Footer from 'components/Footer'


const Catalog: NextPage = () => {
  const {app} = useSelector((state) => state);
  const dispatch = useDispatch();

  return (
    <>
      <Head>
        <title>Vinhos com descontos especiais | Wine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Filter />
        <ProductList list={wineList} />
      </Container>
      <Footer />
    </>
  ) 
}

export default Catalog
