import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import App from './_app'
import styles from '../styles/Home.module.css'
import { useSelector, useDispatch } from 'react-redux'
import { Actions } from 'store'
import Footer from 'components/Footer'

const Home: NextPage = () => {
  const {app} = useSelector((state) => state);
  const dispatch = useDispatch();

  return (
    <div className={styles.container}>
      <Head>
        <title>Vinhos com descontos especiais | Wine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Link href="/catalog">
          <a>Clique aqui para ir para o catálogo de vinhos</a>
        </Link>
      </main>
      <Footer />
    </div>
  ) 
}

export default Home
