import type { NextPage } from 'next'
import Head from 'next/head'
import App from './_app'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vinhos com descontos especiais | Wine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Redirecting to search...
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
